[package]
name = "amelioration"
version = "0.1.0"
authors = ["ESC <youhavethewrong@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
failure = "0.1"
termion = "1.5"
tui = "0.6.2"
